security:
    # ...

    providers:
        in_memory:
             memory:
                  users:
                      ryan:
                          password: ryanpass
                          roles: 'ROLE_USER'
                      admin:
                          password: kitten
                          roles: 'ROLE_ADMIN'
    encoders:
            Symfony\Component\Security\Core\User\User: plaintext
    firewalls:
        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
            logout:
                path:   /logout
                target: /

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/person/*, roles: ROLE_ADMIN }
        - { path: ^/list, roles: ROLE_ADMIN }
        - { path: ^/file-download/*, roles: ROLE_ADMIN }
        - { path: /, roles: IS_AUTHENTICATED_ANONYMOUSLY }
