person:
    path: /
    controller: App\Controller\PersonController::person
    methods: [GET,POST]

#savePerson:
#    path: /
#    controller: App\Controller\PersonController::save
#    methods: [POST]

list:
    path: /list
    controller: App\Controller\PersonController::list

details:
    path: /person/{id}
    controller: App\Controller\PersonController::details
    requirements:
        page: '\d+'

fileDownload:
    path: /person-file/{fileName}
    controller:  App\Controller\PersonController::fileDownload

login:
    path: /login
    controller: App\Controller\SecurityController::login

logout:
    path: /logout # no need controller method - logs out automatically

