person:
    path: /
    controller: App\Controller\PersonController::person
    methods: [GET,POST]

#savePerson:
#    path: /
#    controller: App\Controller\PersonController::save
#    methods: [POST]

list:
    path: /list
    controller: App\Controller\PersonController::list

uploadTest:
    path: /upload
    controller: App\Controller\ProductController::new